<a href="https://colab.research.google.com/github/jyothishri184/Machine-Learning-Algorithms/blob/main/8_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import svm

In [ ]:
df_test = pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/test.csv")
df_train = pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/train.csv")

PREPROCESSING OF TRAIN DATASET

In [ ]:
df_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df_train.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
df_train.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [ ]:
df_train.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
df_train[df_train.Embarked.isna()]

     Survived  Pclass     Sex   Age  SibSp  Parch  Fare Cabin Embarked
61          1       1  female  38.0      0      0  80.0   B28      NaN
829         1       1  female  62.0      0      0  80.0   B28      NaN

In [ ]:
df_train[df_train.Age.isna()]

     Survived  Pclass     Sex  Age  SibSp  Parch     Fare Cabin Embarked
5           0       3    male  NaN      0      0   8.4583   NaN        Q
17          1       2    male  NaN      0      0  13.0000   NaN        S
19          1       3  female  NaN      0      0   7.2250   NaN        C
26          0       3    male  NaN      0      0   7.2250   NaN        C
28          1       3  female  NaN      0      0   7.8792   NaN        Q
..        ...     ...     ...  ...    ...    ...      ...   ...      ...
859         0       3    male  NaN      0      0   7.2292   NaN        C
863         0       3  female  NaN      8      2  69.5500   NaN        S
868         0       3    male  NaN      0      0   9.5000   NaN        S
878         0       3    male  NaN      0      0   7.8958   NaN        S
888         0       3  female  NaN      1      2  23.4500   NaN        S

[177 rows x 9 columns]

In [ ]:
df_train[df_train.Cabin.isna()]

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
2           1       3  female  26.0      0      0   7.9250   NaN        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
5           0       3    male   NaN      0      0   8.4583   NaN        Q
7           0       3    male   2.0      3      1  21.0750   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
884         0       3    male  25.0      0      0   7.0500   NaN        S
885         0       3  female  39.0      0      5  29.1250   NaN        Q
886         0       2    male  27.0      0      0  13.0000   NaN        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[687 rows x 9 columns]

In [ ]:
#we have to fill null values age,embarked,cabin
#convert object to int

In [ ]:
#cabin has many nan almost 80% hence drop cabin
df_train.drop('Cabin',axis=1,inplace=True)
df_train

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
#since s is more replace all Nan with s
df_train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
df_train['Embarked']=df_train['Embarked'].fillna("S")

In [ ]:
#for filling age
df_train['Age']=df_train['Age'].fillna(df_train['Age'].median())
df_train.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [ ]:
df_train['Sex']=df_train['Sex'].replace(['male','female'],[0,1])
df_train['Embarked']=df_train['Embarked'].replace(['S','C','Q'],[1,2,3])
df_train

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    0  22.0      1      0   7.2500         1
1           1       1    1  38.0      1      0  71.2833         2
2           1       3    1  26.0      0      0   7.9250         1
3           1       1    1  35.0      1      0  53.1000         1
4           0       3    0  35.0      0      0   8.0500         1
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    0  27.0      0      0  13.0000         1
887         1       1    1  19.0      0      0  30.0000         1
888         0       3    1  28.0      1      2  23.4500         1
889         1       1    0  26.0      0      0  30.0000         2
890         0       3    0  32.0      0      0   7.7500         3

[891 rows x 8 columns]

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB

PRE PROCESSING OF TEST DATASET

In [ ]:
df_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df_test.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
df_test.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       3    male  34.5      0      0   7.8292   NaN        Q
1       3  female  47.0      1      0   7.0000   NaN        S
2       2    male  62.0      0      0   9.6875   NaN        Q
3       3    male  27.0      0      0   8.6625   NaN        S
4       3  female  22.0      1      1  12.2875   NaN        S

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    object
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Fare      417 non-null    float64
 6   Cabin     91 non-null     object
 7   Embarked  418 non-null    object
dtypes: float64(2), int64(3), object(3)
memory usage: 26.2+ KB

In [ ]:
df_test.isna().sum()

Pclass        0
Sex           0
Age          86
SibSp         0
Parch         0
Fare          1
Cabin       327
Embarked      0
dtype: int64

In [ ]:
df_test[df_test.Age.isna()]

     Pclass     Sex  Age  SibSp  Parch     Fare Cabin Embarked
10        3    male  NaN      0      0   7.8958   NaN        S
22        1  female  NaN      0      0  31.6833   NaN        S
29        3    male  NaN      2      0  21.6792   NaN        C
33        3  female  NaN      1      2  23.4500   NaN        S
36        3  female  NaN      0      0   8.0500   NaN        S
..      ...     ...  ...    ...    ...      ...   ...      ...
408       3  female  NaN      0      0   7.7208   NaN        Q
410       3  female  NaN      0      0   7.7500   NaN        Q
413       3    male  NaN      0      0   8.0500   NaN        S
416       3    male  NaN      0      0   8.0500   NaN        S
417       3    male  NaN      1      1  22.3583   NaN        C

[86 rows x 8 columns]

In [ ]:
df_test[df_test.Cabin.isna()]

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         3    male  34.5      0      0   7.8292   NaN        Q
1         3  female  47.0      1      0   7.0000   NaN        S
2         2    male  62.0      0      0   9.6875   NaN        Q
3         3    male  27.0      0      0   8.6625   NaN        S
4         3  female  22.0      1      1  12.2875   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
412       3  female  28.0      0      0   7.7750   NaN        S
413       3    male   NaN      0      0   8.0500   NaN        S
415       3    male  38.5      0      0   7.2500   NaN        S
416       3    male   NaN      0      0   8.0500   NaN        S
417       3    male   NaN      1      1  22.3583   NaN        C

[327 rows x 8 columns]

In [ ]:
#we have to fill null values age,cabin,fare
#convert object to int
#cabin has many nan almost 80% hence drop cabin
df_test.drop('Cabin',axis=1,inplace=True)
df_test

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [ ]:
#for filling age
df_test['Age']=df_test['Age'].fillna(df_test['Age'].median())
df_test

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male  27.0      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male  27.0      0      0    8.0500        S
417       3    male  27.0      1      1   22.3583        C

[418 rows x 7 columns]

In [ ]:
df_test.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [ ]:
df_test.dropna(inplace=True)
df_test.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 417 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    417 non-null    int64
 1   Sex       417 non-null    object
 2   Age       417 non-null    float64
 3   SibSp     417 non-null    int64
 4   Parch     417 non-null    int64
 5   Fare      417 non-null    float64
 6   Embarked  417 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 26.1+ KB

In [ ]:
df_test['Sex']=df_test['Sex'].replace(['male','female'],[0,1])
df_test['Embarked']=df_test['Embarked'].replace(['S','C','Q'],[1,2,3])
df_test

     Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0         3    0  34.5      0      0    7.8292         3
1         3    1  47.0      1      0    7.0000         1
2         2    0  62.0      0      0    9.6875         3
3         3    0  27.0      0      0    8.6625         1
4         3    1  22.0      1      1   12.2875         1
..      ...  ...   ...    ...    ...       ...       ...
413       3    0  27.0      0      0    8.0500         1
414       1    1  39.0      0      0  108.9000         2
415       3    0  38.5      0      0    7.2500         1
416       3    0  27.0      0      0    8.0500         1
417       3    0  27.0      1      1   22.3583         2

[417 rows x 7 columns]

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 417 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    417 non-null    int64
 1   Sex       417 non-null    int64
 2   Age       417 non-null    float64
 3   SibSp     417 non-null    int64
 4   Parch     417 non-null    int64
 5   Fare      417 non-null    float64
 6   Embarked  417 non-null    int64
dtypes: float64(2), int64(5)
memory usage: 26.1 KB

In [ ]:
features=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']
C=0.7 #margin
model=svm.SVC(kernel='linear',C=C).fit(df_train[features],df_train['Survived'])

In [ ]:
y_pred=model.predict(df_test)

NameError: ignored